spring.application.name=projectCalcTool

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3307/project_calc}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

spring.thymeleaf.cache=false
